# Generated by Django 4.1.1 on 2022-10-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIntervalsBRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('room_id', models.CharField(max_length=10)),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EventBRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('type', models.IntegerField(choices=[(32, 'Motion'), (21, 'Calm')])),
            ],
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
